<!--About Us Banner-->
<section class="about-banner-wrapper bg-aside">
    <div class="container container-wrapper">
        <div class="bottom-overlay"></div>
        <div class="banner-text">
            <h1>About Us</h1>
            <div class="sub-banner">
                <p>We offer comprehensive learning solutions to leading MNCs, Indian business houses, SMEs, would be unicorn startups, leading universities and Individuals. We believe in partnering with our esteemed clients for effective delivery of results and learning outcomes. We aim to enhance the effectiveness and potential of an individual.</p>
            </div>
        </div>
    </div>
</section>
<!--About Us Banner-->

<!--About Content-->
<section class="bg-grey ptb-3 about-content-wrapper">
    <div class="container container-wrapper">
        <p>Any learning activity is a complex cognitive process and at MLS, we believe that the effectiveness of any learning process is based on how deeply we ENGAGE the learner, ENABLE him/her to adopt, adapt, perform and become proficient, how is the learner able to EVOLVE.</p>
        <p>Thus, our program design and delivery are based on the 3E principle – engaging the learner meaningfully, enabling him/her to acquire skills and competencies, which ultimately sets him/ her on a path to ‘evolve’.</p>
        <div class="img-wrapper">
            <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/about-desc-img.png'); ?>" alt="" class="mw-100">
        </div>
        <p> Our expertise in delivering learning solutions to critical business problems is used to bridge the skill gap between corporate and academia. We provide training to enhance employability of management and engineering graduates. Starting from communication skills, attitude building to structured interventions on personal effectiveness, we handle the entire corporate grooming life cycle.</p>
        <p>Due to our solution-focused approach, our training programs are considered as highly effective in domains such as employee engagement, enhancing managerial effectiveness, negotiation skills and leadership development initiatives.</p>
        <p>MLS has a long-standing engagement with our clients due to its ‘Value Delivery approach’. We deliver learning solutions to critical business problems, structured interventions to improve individual and organisational performance. Do browse through this website to know more about our learning philosophy, services offered and list of esteemed clients.</p>
        <div class="connect-wrapper">
            <p>Together, we can make a positive difference! We are just a call/ text away.</p>
            <div class="img-wrapper">
                <a href="<?php echo $url->getWhatsAppMsgUrl(); ?>" target="_blank">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/contact-now.png'); ?>" alt="" class="mw-100">
                </a>
            </div>
        </div>
    </div>
</section>
<!--About Content-->

<!--Our Focus-->

<h4 class="about-page-title ptb-3" id="meridian-focus">OUR FOCUS</h4>
<section class="bg-grey ptb-5 about-focus-wrapper">
    <div class="container container-wrapper">
        <div class="row focus-category">
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 title-wrapper">
                <div class="focus-title">
                    <h2>The Context</h2>
                </div>
                <div class="focus-para">
                    <p>Taking into account the people, culture, workplace, curriculum.</p>
                    <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/context.png'); ?>" alt="" class="mw-100">
                </div>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 title-wrapper">
                <div class="focus-title">
                    <h2>The Concept</h2>
                </div>
                <div class="focus-para">
                    <p>Simple, relatable and easy to understand idea.</p>
                    <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/concept.png'); ?>" alt="" class="mw-100">
                </div>
            </div>
        </div>
        <div class="row focus-category">
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 title-wrapper">
                <div class="focus-title">
                    <h2>The Content</h2>
                </div>
                <div class="focus-para">
                    <p class="sec-line">Designed using 4MAT methodology to create dynamic and engaging learning.</p>
                    <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/content.png'); ?>" alt="" class="mw-100">
                </div>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 title-wrapper">
                <div class="focus-title">
                    <h2>The Delivery</h2>
                </div>
                <div class="focus-para">
                    <p class="sec-line"> Catering to the 4 types of learners: Innovative, Analytic, Common Sense and Dynamic, thereby developing an intrinsic learning attitude and solution-oriented mindset in all our learners offering benefit realisation for the organisation.</p>
                    <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/delivery.png'); ?>" alt="" class="mw-100">
                </div>
            </div>
        </div>
    </div>
</section>
<!--Our Focus-->

<!--hr-->
<hr class="purple-line">
<!--hr-->

<!--OUR Philosophy and Approachs-->
<section class="bg-white ptb-5 about-focus-wrapper philo-wrapper" id="meridian-philosophy-and-approach">
    <div class="container container-wrapper">
        <h4 class="about-page-title">OUR Philosophy and Approach</h4>
        <p class="mt-4">At MLS, we believe in the philosophy of experiential learning by Kolb (1984). The learner is exposed to real-life situations, simulations which propels his/her thought process. Our experienced trainers channelize his/her thoughts and behaviour in the right direction. So we act as ‘facilitators’ than the traditional teachers. This learning method is known for higher learning retention and better results for individuals and organizations. Whether it is a senior business leader or an engineering graduate, experiential learning techniques makes the learning process a joyful activity.</p>
        <p>We follow a case-based approach, conduct simulated discussions and apply design thinking methods to unearth, explore and solve a business problem. Taking a clue from these discussions, we train budding managers and Engineering professionals for upcoming challenges and opportunities. Our organization has effectively executed various training programs for individuals and corporate effectively, making a positive contribution to the learning process.</p>
        <p>To know more about experiential learning and our programs based on this philosophy, <a href="<?php echo $url->getUri('connect') ?>"><span class="bold-text">do connect with us.</span></a></p>
        <div class="img-wrapper">
            <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/philosophy-and-approach.png'); ?>" alt="" class="mw-100">
        </div>
    </div>
</section>
<!--OUR Philosophy and Approach-->

<!--hr-->
<hr class="purple-line">
<!--hr-->

<!--Testimonials-->
<section class="bg-white pt-5 pb-8 testimonials-wrapper testim-wrapper about-focus-wrapper" id="meridian-testimonials">
    <div class="container container-wrapper">
        <h4 class="about-page-title">Testimonials</h4>
        <div class="row" id="testimonial-slider">
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div class="key-areas-wrapper mt-3">
                    <div class="key-area-list">
                        <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/quote.svg'); ?>" alt="" class="quotes mw-100 mb-4">
                        <div>
                            <input type="checkbox" class="read-more-state" id="post-1" />

                            <p class="read-more-wrap">Damini is someone who has exceptional expertise in leadership coaching. I have been a student of her for a couple of leadership courses. What I like most is her unique coaching style, her knowledge about the subject and her passion for anything<span class="read-more-target">  that she does.I still use my notes from her training and every time I refer those, they show me some more insights on the topics and examples Damini uses during those courses. Keep up the good work and I wish you all the best for your future endeavours!!</span></p>
                            
                            <label for="post-1" class="read-more-trigger"></label>
                        </div>
                    </div>
                    <div class="testi-name">
                        <p>-Vyankatesh Papinwar</p>
                    </div>
                </div>
                <div class="logo-img-wrapper">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/Deutsche-Bank.png'); ?>" alt="">
                </div>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div class="key-areas-wrapper mt-3">
                    <div class="key-area-list">
                        <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/quote.svg'); ?>" alt="" class="quotes mw-100">
                        <p class="mt-4">The Best about Soudamini's work style is that she knows what she has to do and knows the actual practical approach that any assignment demands. Her quality of relating to her young participants makes her a stand out trainer from the crowd. </p>
                    </div>
                    <div class="testi-name">
                        <p>-Mehul Soratiya,</p>
                        <p>Informatica Cloud Developer & Instructor</p>
                    </div>
                </div>
                <div class="logo-img-wrapper">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/Saama.png'); ?>" alt="">
                </div>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div class="key-areas-wrapper key-areas-wrapper-3 mt-3">
                    <div class="key-area-list">
                        <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/quote.svg'); ?>" alt="" class="quotes mw-100 mb-4">
                        <div>
                            <input type="checkbox" class="read-more-state" id="post-3" />
                            <p class="read-more-wrap">Hi Soudamini,
                            It has always been a wonderful experience to work with you. What I have observed during the training engagement and feedback of the training is that;
                            <span class="read-more-target">You are an interesting combination of being People sensitive, solution-focused and result-oriented. I have seen that you put in great efforts to understand the business needs, deliverables and specific challenges. Your approach and solutions were flexible to accommodate our specific expectations.
                            Your sincerity and dedication at work is a classic example of client centricity and setting a new bar of excellence every time.
                            I would strongly recommend you for conceptualizing, planning and offering a people-centric, business-focused solution in my future engagements as well
                            Wish you all the best</span></p>   
                            <label for="post-3" class="read-more-trigger"></label>
                        </div>
                    </div>
                    <div class="testi-name">
                        <p>-Vishal Agarwal,</p>
                        <p>Global Technical Training Manager</p>
                    </div>
                </div>
                <div class="logo-img-wrapper">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/Fujitsu.png'); ?>" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<!--Testimonials-->

<!--Gallery-->
<section class="bg-grey ptb-5 gallery-wrapper about-focus-wrapper">
    <div class="container container-wrapper">
        <h4 class="about-page-title">Gallery</h4>
        <div class="row gallery-slider" id="gallery-slider-wrapper">
            <div>
                <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/g-1.png'); ?>" alt="">
            </div>
            <div>
                <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/g-2.png'); ?>" alt="">
            </div>
            <div>
                <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/g-3.png'); ?>" alt="">
            </div>
            <div>
                <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/g-4.png'); ?>" alt="">
            </div>
            <div>
                <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/g-5.png'); ?>" alt="">
            </div>
            <div>
                <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/g-6.png'); ?>" alt="">
            </div>
            <div>
                <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/g-7.png'); ?>" alt="">
            </div>
            <div>
                <img src="<?php echo $tag->getImageUri('assets/front/images/about-us/g-8.png'); ?>" alt="">
            </div>
        </div>
    </div>
</section>
<!--Gallery-->