
<!--Coming Soon-->
<section class="coming-soon-wrapper">
    <div class="container-fluid">
        <div class="row coming-soon-row">
            <div class="col-5 text-wrapper">
                <div class="coming-soon-text-wrapper">
                    <h1>Under Development</h1>
                    <p>We are working hard to give you better experience with our new impressive site</p>
                    <p class="text-purple">STAY CONNECTED, STAY UPDATED</p>
                </div>
                <div class="follow-wrapper">
                    <p>FOLLOW US HERE :</p>
                    <div class="social-media-wrapper">
                        <div class="container p-0">
                            <div class="row">
                                <div class="col-12">
                                    <ul>
                                        <li>
                                            <a href="<?php echo $url->getWhatsAppMsgUrl(); ?>" target="_blank">
                                                <img src="<?php echo $tag->getImageUri('assets/front/images/WhatsApp_white (1).svg'); ?>" alt="">
                                            </a>
                                        </li>
                                        <li>
                                            <a href="https://www.facebook.com/Meridian-Learning-Solutions-100200838275142" target="_blank">
                                                <img src="<?php echo $tag->getImageUri('assets/front/images/Facebook_white.svg'); ?>" alt="">
                                            </a>
                                        </li>
                                        <li>
                                            <a href="https://www.linkedin.com/company/meridian-learning-solutions" target="_blank">
                                                <img src="<?php echo $tag->getImageUri('assets/front/images/LinkedIN_white.svg'); ?>" alt="">
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-7 img-wrapper">
                <img src="<?php echo $tag->getImageUri('assets/front/images/coming-soon.png'); ?>" alt="">
            </div>
        </div>
    </div>
</section>
<!--Coming Soon-->
