
<!--Connect Banner-->
<section class="connect-wrapper bg-aside">
    <div class="container container-wrapper">
        <div class="overlay-wrapper"></div>
        <div class="bottom-overlay"></div>
            <div class="banner-text">
                <h1>Connect With Us</h1>
            </div>
    </div>
</section>
<!--Connect Banner-->

<!--Contact Form-->
<section class="bg-grey contact-sec">
    <div class="container container-wrapper">
        <div class="row cont-row">
            <form role="form" id="contact-form" class="contact-form">
                <div class="row ">
                    <div class="col-md-6">
                        <div class="form-group">
                        <input type="text" class="form-control" name="name" autocomplete="off" id="name" placeholder="Name">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                        <input type="tel" class="form-control" name="mob" autocomplete="off" id="mob" placeholder="Mobile no.">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <input type="email" class="form-control" name="email" autocomplete="off" id="email" placeholder="Email">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <input type="text" class="form-control" name="subj" autocomplete="off" id="subj" placeholder="Subject">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                        <textarea class="form-control textarea" rows="3" name="Message" id="Message" placeholder="Message"></textarea>
                        </div>
                    </div>
                </div>
                <div class="row submit-btn">
                    <div class="col-md-12">
                        <button type="submit" class="btn main-btn pull-right">Send a message</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="contact-social-media">
            <div class="connect-wrapper">
                <p>Connect with us</p>
                <ul class="info">
                    <li>
                        <a href="tel:+ 91 880 670 8864"><img src="<?php echo $tag->getImageUri('assets/front/images/phone.svg'); ?>" alt="">+ 91 880 670 8864</a>
                    </li>
                    <li>
                        <a href="mailto:info@meridianlearningsolutions.com"><img src="<?php echo $tag->getImageUri('assets/front/images/mail.svg'); ?>" alt="">info@meridianlearningsolutions.com</a>
                    </li>
                </ul>
            </div> 
            <div class="social-media-wrapper">
                <ul>
                    <li>
                        <a href="">
                            <img src="<?php echo $tag->getImageUri('assets/front/images/whatsapp.svg'); ?>" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/Meridian-Learning-Solutions-100200838275142" target="_blank">
                            <img src="<?php echo $tag->getImageUri('assets/front/images/fb.svg'); ?>" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/company/meridian-learning-solutions" target="_blank">
                            <img src="<?php echo $tag->getImageUri('assets/front/images/linkedin.svg'); ?>" alt="">
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!--Contact Form-->
