<!--Home Banner-->
<section class="home-wrapper bg-aside">
    <div class="container container-wrapper">
        <div class="bottom-overlay"></div>
        <div class="top-overlay"></div>
            <div class="">
                <div class="row">
                    <div class="col-5 home-banner-text">
                        <span>Welcome To</span>
                        <h1>Meridian Learning Solutions</h1>
                        <span>Your Partner in Evolutionary Learning</span>
                        <div class="banner-para">
                            <p>BASED ON 3E PRINCIPLE : ENGAGE the learner meaningfully, ENABLE the learner to acquire skills and competencies, setting the learner on a path to ‘EVOLVE’.</p>
                        </div>
                        <div class="banner-btn">
                            <a href="<?php echo $url->getUri('services') ?>">Read More</a>
                        </div>
                    </div>
                    <div class="col-md-7 home-banner-wrapper">
                        <div class="row">
                            <div class="col-md-12 p-0">
                                <div class="img-overlay"></div>
                                <img src="<?php echo $tag->getImageUri('assets/front/images/home/home-banner.png'); ?>" alt="">
                            </div>
                        </div>
                        <div class="row banner-img-sec">
                            <div class="col-md-12 p-0">
                                <img src="<?php echo $tag->getImageUri('assets/front/images/home/home-banner-1.png'); ?>" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="banner-para-2 mt-5">
                <p>
                Under Meridian Learning Solutions, we offer various structured interventions and consulting services to the corporate and academic sector.
                </p>
            </div>
    </div>
</section>
<!--Home Banner-->

<!--Key Areas of Engagement-->
<section class="bg-grey key-areas-sec ptb-8">
    <h4>KEY AREAS OF ENGAGEMENT</h4>
    <div class="container container-wrapper">
        <div class="row pt-5">
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <h2>
                    Competency Development
                </h2>
                <div class="key-areas-wrapper mt-5">
                <img src="<?php echo $tag->getImageUri('assets/front/images/home/key-areas-1.png'); ?>" alt="" class="mw-100">
                    <div class="key-area-list">
                        <ul class="p-0 list-style-none">
                            <li>Corporates</li>
                            <li>ACADEMIA</li>
                            <li>INDIVIDUALS</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <h2>
                    HR & OD Initiatives
                </h2>
                <div class="key-areas-wrapper mt-5">
                <img src="<?php echo $tag->getImageUri('assets/front/images/home/key-areas-2.png'); ?>" alt="" class="mw-100">
                    <div class="key-area-list">
                        <ul class="p-0 list-style-none">
                            <li>Developing & Nurturing Learning Ecosystem </li>
                            <li>Employee Engagement and Life Cycle Management</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <h2>
                    Client Relation Management
                </h2>
                <div class="key-areas-wrapper mt-5">
                <img src="<?php echo $tag->getImageUri('assets/front/images/home/key-areas-3.png'); ?>" alt="" class="mw-100">
                    <div class="key-area-list">
                        <ul class="p-0 list-style-none">
                            <li>ASSERTIVE COMMUNICATION</li>
                            <li>LISTENING EFFECTIVELY</li>
                            <li>PERSUASION AND STRATEGIC NEGOTIATIONS</li>
                            <li>SITUALIONAL HANDLING</li>
                            <li>CLIENT INTERACTION SKILLS</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--Key Areas of Engagement-->

<!--Our Focus and Philosophy-->
<section class="focus-philo-wrapper ptb-8 bg-purple bg-corners">
    <div class="container container-wrapper">
        <div class="row">
            <div class="our-focus-wrapper-img bg-white">
                <div class="our-focus-wrapper">
                    <h4>OUR FOCUS</h4>
                    <p>Developing an intrinsic learning attitude and solution-oriented mindset in all our learners</p>
                    <div class="read-more-btn">
                        <a href="<?php echo $url->getUri('services') ?>">Read More</a>
                    </div>
                </div>
                <div class="our-focus-img-wrap">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/home/our-focus.png'); ?>" alt="">
                </div>
            </div>
            <div class="philo-approach-wrapper bg-white">
                <div class="our-focus-wrapper">
                    <h4>PHILOSOPHY AND APPROACH</h4>
                    <p>Making learning a joyful journey for the learners through Experiential Learning Techniques</p>
                    <div class="read-more-btn">
                        <a href="<?php echo $url->getUri('services') ?>">Read More</a>
                    </div>
                </div>
                <div class="our-focus-img-wrap">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/home/approach.png'); ?>" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<!--Our Focus and Philosophy-->

<!--Testimonials-->
<section class="testimonials-wrapper ptb-8">
    <div class="container container-wrapper">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                <img src="<?php echo $tag->getImageUri('assets/front/images/home/testimonials.png'); ?>" alt="" class="mw-100">
            </div>
            <div class="col-lg-5 col-md-12 col-sm-12 col-xs-12">
                <div class="testi-wrapper text-center bg-grey b-50">
                    <h4>Testimonials</h4>
                    <p>SOME GREAT FEEDBACK FROM REPUTED PERSONALITIES</p>
                    <div class="continue-reading">
                        <a href="<?php echo $url->getUri('about-us') ?>" class="continue">Continue Reading</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="testi-wrapper text-center bg-grey b-50">
                    <h4>CONNECT WITH US</h4>
                    <p>FOR QUERIES AND MORE INFO.</p>
                    <div class="continue-reading">
                        <a href="<?php echo $url->getUri('connect') ?>" class="contact">Contact Us</a>
                        <a href="#" target="_blank" class="icon">
                            <img src="<?php echo $tag->getImageUri('assets/front/images/home/WhatsApp.svg'); ?>" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--Testimonials-->