<!--Home Banner-->
<section class="home-wrapper bg-aside">
    <div class="container container-wrapper">
        <div class="bottom-overlay"></div>
        <div class="top-overlay"></div>
            <div class="">
                <div class="row">
                    <div class="col-5 home-banner-text">
                        <span>Welcome To</span>
                        <h1>Meridian Learning Solutions</h1>
                        <span>Your Partner in Evolutionary Learning</span>
                        <div class="banner-para">
                            <p>We offer various structured interventions and consulting services to the corporate and academic sector.</p>
                            <p>BASED ON 3E PRINCIPLE : ENGAGE the learner meaningfully, ENABLE the learner to acquire skills and competencies, setting the learner on a path to ‘EVOLVE’.</p>
                        </div>
                        <div class="banner-btn">
                            <a href="<?php echo $url->getUri('services') ?>">Read More</a>
                        </div>
                    </div>
                    <div class="col-md-7 home-banner-wrapper">
                        <div class="row">
                            <div class="col-md-12 p-0">
                                <div class="img-overlay"></div>
                                <img src="<?php echo $tag->getImageUri('assets/front/images/home/home-banner.png'); ?>" alt="">
                            </div>
                        </div>
                        <div class="row banner-img-sec">
                            <div class="col-md-12 p-0">
                                <img src="<?php echo $tag->getImageUri('assets/front/images/home/home-banner-1.png'); ?>" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="banner-para-2 mt-5">
               
            </div>
    </div>
</section>
<!--Home Banner-->

<!--Key Areas of Engagement-->
<section class="bg-grey key-areas-sec engagement-sec ptb-8">
    <h4><a href="<?php echo $url->getUri('services') ?>">KEY AREAS OF ENGAGEMENT</a></h4>
    <div class="container container-wrapper">
        <div class="row pt-5">
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">    
                <a href="<?php echo $url->getUri('services#competency-development') ?>">
                <h2>
                    Competency Development
                </h2>
                <div class="key-areas-wrapper mt-3">
                <img src="<?php echo $tag->getImageUri('assets/front/images/home/key-areas-1.png'); ?>" alt="" class="mw-100">
                    <div class="key-area-list">
                        <ul class="p-0 list-style-none">
                            <li>Corporates</li>
                            <li>Academia</li>
                            <li>Individuals</li>
                        </ul>
                    </div>
                </div>
                </a>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <a href="<?php echo $url->getUri('services#hr-and-od-initiatives') ?>">
                <h2>
                    HR & OD Initiatives
                </h2>
                <div class="key-areas-wrapper mt-3">
                <img src="<?php echo $tag->getImageUri('assets/front/images/home/key-areas-2.png'); ?>" alt="" class="mw-100">
                    <div class="key-area-list">
                        <ul class="p-0 list-style-none">
                            <li>Developing & Nurturing Learning Ecosystem </li>
                            <li>Employee Engagement & Life Cycle Management</li>
                        </ul>
                    </div>
                </div>
                </a>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <a href="<?php echo $url->getUri('services#strategic-crm') ?>">
                <h2>
                    Client Relation Management
                </h2>
                <div class="key-areas-wrapper key-areas-wrapper-3 mt-3">
                <img src="<?php echo $tag->getImageUri('assets/front/images/home/key-areas-3.png'); ?>" alt="" class="mw-100">
                    <div class="key-area-list">
                        <ul class="p-0 list-style-none">
                            <li>Assertive Communication</li>
                            <li>Listening Effectively</li>
                            <li>Persuasion & Strategic Negotiations</li>
                            <li>Situational Handling</li>
                            <li>Client Interaction Skills</li>
                        </ul>
                    </div>
                </div>
                </a>
            </div>
        </div>
    </div>
</section>
<!--Key Areas of Engagement-->

<!--Our Focus and Philosophy-->
<section class="focus-philo-wrapper ptb-8 bg-purple bg-corners">
    <div class="container container-wrapper">
        <div class="row">
            <div class="our-focus-wrapper-img bg-white">
                <div class="our-focus-wrapper ">
                    <h4 class="focus">FOCUS</h4>
                    <p>Developing an intrinsic learning attitude and solution-oriented mindset in all our learners</p>
                    <div class="read-more-btn">
                        <a href="<?php echo $url->getUri('about-us#meridian-focus') ?>">Read More</a>
                    </div>
                </div>
                <div class="our-focus-img-wrap">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/home/our-focus.png'); ?>" alt="">
                </div>
            </div>
            <div class="philo-approach-wrapper bg-white">
                <div class="our-focus-wrapper">
                    <h4>PHILOSOPHY AND APPROACH</h4>
                    <p>Making learning a joyful journey for the learners through Experiential Learning Techniques</p>
                    <div class="read-more-btn">
                        <a href="<?php echo $url->getUri('about-us#meridian-philosophy-and-approach') ?>">Read More</a>
                    </div>
                </div>
                <div class="our-focus-img-wrap">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/home/approach.png'); ?>" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<!--Our Focus and Philosophy-->

<!--Testimonials-->
<section class="testimonials-wrapper ptb-8">
    <div class="container container-wrapper">
        <div class="row">
            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                <img src="<?php echo $tag->getImageUri('assets/front/images/home/testimonials.png'); ?>" alt="" class="testi-img">
            </div>
            <div class="col-lg-5 col-md-12 col-sm-12 col-xs-12">
                <div class="testi-wrapper text-center bg-grey b-50">
                    <h4>Testimonials</h4>
                    <p>Feedback from our esteemed clients</p>
                    <div class="continue-reading">
                        <a href="<?php echo $url->getUri('about-us#meridian-testimonials') ?>" class="continue">Continue Reading</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="testi-wrapper text-center bg-grey b-50">
                    <h4>CONNECT WITH US</h4>
                    <p>For Queries & More Info.</p>
                    <div class="continue-reading">
                        <a href="<?php echo $url->getUri('connect') ?>" class="contact">Connect</a>
                        <a href="<?php echo $url->getWhatsAppMsgUrl(); ?>" target="_blank" class="icon">
                            <img src="<?php echo $tag->getImageUri('assets/front/images/home/WhatsApp.svg'); ?>" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--Testimonials-->