<!--404 Page-->
<div class="section-wrapper sec-width ptb-error">
    <div class="container container-wrapper">
        <div class="error-msg-wrapper">
            <h1>Whoops!</h1>
            <div class="error-text">
                <p>The page you are looking for could not be found.</p>
                <p>It might have been removed, renamed, or did not exist in the first place.</p>
            </div>
            <div class="go-back-btn">
                <a href="<?php echo $url->getUri() ?>">Go Back</a>
            </div>
        </div>
        <div class="error-img-wrapper">
            <img src="<?php echo $tag->getImageUri('assets/front/images/404-img.png'); ?>" alt="">
        </div>
    </div>
</div>
<!--404 Page-->
