
<!--Services Banner-->
<section class="service-banner-wrapper bg-aside">
    <div class="container container-wrapper">
        <div class="bottom-overlay"></div>
            <div class="banner-text">
                <h1>Services</h1>
                <div class="sub-banner">
                    <p class="text-center">MLS offers a comprehensive range of learning solutions to Corporate, SMEs, Academics and Individuals. Have a look at our offerings. If you are looking for a solution, customised to your specific needs, we are just a call/ text away.</p>
                </div>      
            </div>
    </div>
</section>
<!--Services Banner-->

<!--Key Areas of Engagement-->
<section class="service-key-areas">
    <div class="container container-wrapper">
        <h2 class="text-center">KEY AREAS OF ENGAGEMENT</h2>
        <hr class="black-line">
        <div class="tab-list">
            <ul>
                <li>
                    <a class="tab-link" href="#competency-development">Competency Development</a>
                </li>
                <li>
                    <a class="tab-link" href="#hr-and-od-initiatives">HR and OD Initiatives</a>
                 </li>
                <li>
                    <a class="tab-link" href="#strategic-crm">Strategic Client Relationship Management</a>
                </li>
            </ul>
        </div>
    </div>
</section>
<!--Key Areas of Engagement-->

<div class="wrapper-1 size_chart" id="option1">
<!--Competency Development Title-->
<section class="service-main-wrapper key-areas-sec ptb-5" id="competency-development">
    <div class="container container-wrapper">
        <h4 class="text-center">
            <span class="competency-title">
                Competency Development
            </span>
        </h4>
    </div>
</section>
<!--Competency Development Title-->

<!--Sub-Categories-1-->
<section class="service-cat-wrapper ptb-5 bg-grey">
    <div class="container container-wrapper">
        <h4 class="text-center">
            CORPORATES
        </h4>
        <div class="row sub-category">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 bg-white cat-wrapper">
                <h2>
                    Managerial Skills/ Leadership Development
                </h2>
                <div class="row cat-listing-wrapper">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <ul>
                            <li>First-time Managers</li>
                            <li>Managerial Effectiveness</li>
                            <li>Coaching and Feedback</li>
                            <li>Managing Change Effectively</li>
                            <li>Communicating Assertively</li>
                            <li>High Impact Presentations</li>
                            <li>Goal Setting for Teams</li>
                            <li>Situational Leadership</li>
                            <li>Managing Conflict</li>
                        </ul>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 service-img-wrapper">
                        <img src="<?php echo $tag->getImageUri('assets/front/images/service/managerial-skills.png'); ?>" alt="">
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 bg-white cat-wrapper">
                <h2>
                    Sales & Services
                </h2>
                <div class="row cat-listing-wrapper">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <ul>
                            <li>Sales Excellence</li>
                            <li>The Art of Value Selling</li>
                            <li>Customer Relationship Management</li>
                            <li>Developing Service Mindset</li>
                            <li>Negotiation Skills</li>
                        </ul>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 service-img-wrapper">
                        <img src="<?php echo $tag->getImageUri('assets/front/images/service/sales.png'); ?>" alt="">
                    </div>
                </div>
            </div>
        </div>

        <div class="row sub-category">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 bg-white cat-wrapper">
                <h2>
                    Behavioural Competency Development
                </h2>
                <div class="row cat-listing-wrapper">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <ul>
                            <li>Effective Time Management</li>
                            <li>Interpersonal Skills</li>
                            <li>Work-life balance/ Stress Management</li>
                            <li>Being Proactive</li>
                            <li>Workplace Etiquette</li>
                            <li>Grooming and Etiquette</li>
                        </ul>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 service-img-wrapper">
                        <img src="<?php echo $tag->getImageUri('assets/front/images/service/behavioral.png'); ?>" alt="">
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 bg-white cat-wrapper">
                <h2>
                    Business Communication
                </h2>
                <div class="row cat-listing-wrapper">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <ul>
                            <li>Presentation Skills</li>
                            <li>Language Enhancement</li>
                            <li>Effective Communication</li>
                            <li>Email Etiquette</li>
                            <li>Telephone Meeting/ Conference Call Etiquette</li>
                            <li>Non – Verbal Communication</li>
                            <li>Cross-Cultural Sensitisation & Global Communication</li>
                        </ul>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 service-img-wrapper">
                        <img src="<?php echo $tag->getImageUri('assets/front/images/service/business.png'); ?>" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--Sub-Categories-1 -->

<!--Sub-Categories-2-->
<section class="service-cat-wrapper service-cat-sec-wrapper pb-3 bg-grey">
    <div class="container container-wrapper">
        <h4 class="text-center">
            ACADEMIA
        </h4>
        <div class="container container-wrapper">
        <div class="row">
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="key-areas-wrapper mt-3">
                <h2>
                    Campus To Corporate
                </h2>
                    <div class="key-area-list">
                        <ul class="listing-points">
                            <li>Employability Enhancement Program</li>
                            <li>Assertiveness and Confidence</li>
                            <li>Effective Communication</li>
                            <li>Aptitude Skills</li>
                            <li>Resume Writing</li>
                            <li>GD and PI</li>
                            <li>Professional Grooming and Etiquettes</li>
                            <li>Personal Effectiveness</li>
                        </ul>
                    </div>
                    <img src="<?php echo $tag->getImageUri('assets/front/images/service/campus-to-corporate.png'); ?>" alt="" class="mw-100">
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="key-areas-wrapper mt-3">
                <h2>
                    Corporate Readiness
                </h2>
                    <div class="key-area-list">
                        <ul class="listing-points">
                            <li>Presenting yourself Effectively</li>
                            <li>Positive Attitude in the Workplace</li>
                            <li>Workplace Etiquette – Personal, Social and Business</li>
                            <li>Handling discussions, meetings, Presentations, working in a team</li>
                            <li>Interview skills – Preparing, Dressing and Hygiene, Time Management and Punctuality, Tips on Handling an Interview</li>
                            <li>Organisation Etiquette</li>
                        </ul>
                    </div>
                    <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-readiness.png'); ?>" alt="" class="mw-100">
                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="key-areas-wrapper key-areas-wrapper-3 mt-3">
                <h2>
                    Faculty Development
                </h2>
                    <div class="key-area-list">
                        <ul class="listing-points">
                            <li>Presentation Skills (Level 1, 2, 3)</li>
                            <li>Leadership Skills</li>
                            <li>Teaching Techniques</li>
                            <li>Communication Skills</li>
                            <li>Confidence Building</li>
                            <li>Presenting yourself</li>
                            <li>Accountability</li>
                            <li>Etiquette – Personal, Social and Business</li>
                            <li>Situation Handling</li>
                        </ul>
                    </div>
                    <img src="<?php echo $tag->getImageUri('assets/front/images/service/faculty-dev.png'); ?>" alt="" class="mw-100">
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
<!--Sub-Categories-2-->

<!--Sub-Categories-3-->
<section class="service-cat-wrapper service-indivi-sec-wrapper ptb-5 bg-grey">
    <div class="container container-wrapper">
        <h4 class="text-center">
            INDIVIDUALS
        </h4>
        <div class="row sub-category">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bg-white cat-wrapper">
                <h2>
                    Personal Effectiveness
                </h2>
                <div class="row cat-listing-wrapper">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <ul>
                            <li>Goal Setting</li>
                            <li>Planning and Prioritizing</li>
                            <li>Managing Timek</li>
                            <li>Stress Management</li>
                            <li>Adapting to Change</li>
                            <li>Public Speaking and Presentation</li>
                            <li>Grooming and Etiquette</li>
                            <li>Personality Development</li>
                            <li>Image management</li>
                            <li>Body language</li>
                        </ul>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 service-img-wrapper">
                        <img src="<?php echo $tag->getImageUri('assets/front/images/service/team-discussion.png'); ?>" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--Sub-Categories-3-->
</div>


<div class="wrapper-2 size_chart" id="option2">
<!--HR and OD Initiatives-->
<section class="service-main-wrapper key-areas-sec ptb-5" id="hr-and-od-initiatives">
    <div class="container container-wrapper">
        <h4 class="text-center">
            <span>
                HR and OD Initiatives
            </span>
        </h4>
    </div>
</section>
<!--HR and OD Initiatives-->

<!--HR Sub Categories-->
<section class="service-cat-wrapper ptb-5 bg-grey">
    <div class="container container-wrapper">
        <div class="row sub-category">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 bg-white cat-wrapper">
                <div class="row hr-cat-listing-wrapper">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <h2>
                            Employee Engagement and Life Cycle Management
                        </h2>
                        <p>Covering entire gamut of employee life cycle management (Engagement initiatives, Structured Learning Interventions and Performance Management System)</p>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 service-img-wrapper">
                        <img src="<?php echo $tag->getImageUri('assets/front/images/service/emp-engagement.png'); ?>" alt="">
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 bg-white cat-wrapper">
                <div class="row hr-cat-listing-wrapper">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <h2>
                            Developing & Nurturing Learning Ecosystem
                        </h2>
                        <p>TNI/ TNA, Recommending, Planning and Organizing Interventions, Setting up Processes, Train the Trainer, Training Effectiveness Management</p>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 service-img-wrapper">
                        <img src="<?php echo $tag->getImageUri('assets/front/images/service/ecosystem.png'); ?>" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--HR Sub Categories-->
</div>


<div class="wrapper-3 size_chart" id="option3">
<!--Strategic Client Relationship Management Title-->
<section class="service-main-wrapper client-service-main-wrapper key-areas-sec ptb-5" id="strategic-crm">
    <div class="container container-wrapper">
        <h4 class="text-center">
            <span>
                Strategic Client Relationship Management
            </span>
        </h4>
    </div>
</section>
<!--Strategic Client Relationship Management Title-->

<!--Strategic CRM Sub Categories-->
<section class="service-cat-wrapper service-cat-sec-wrapper crm-service-cat-wrapper ptb-5 bg-grey">
    <div class="container container-wrapper">
        <p class="text-center">Customised Training programs to improve the efficiency and business performance of your sales and service force.</p>
        <div class="row sub-category">
            <div class="service-img-main mt-4">
                <div class="ser-img">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/service/assertive-communication.png'); ?>" alt="">
                </div>
                <div class="ser-img">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/service/listening-eff.png'); ?>" alt="">
                </div>
                <div class="ser-img">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/service/persuasion-strategic.png'); ?>" alt="">
                </div>
                <div class="ser-img">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/service/sit-handling.png'); ?>" alt="">
                </div>
                <div class="ser-img">
                    <img src="<?php echo $tag->getImageUri('assets/front/images/service/client-interactio-skill.png'); ?>" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<!--Strategic CRM Sub Categories-->
</div>

<!--Strategic Client Relationship Management Title-->
<section class="service-main-wrapper client-service key-areas-sec ptb-5">
    <div class="container container-wrapper">
        <h4 class="text-center">
            <span>
                OUR CLIENTS
            </span>
        </h4>
    </div>
</section>
<!--Strategic Client Relationship Management Title-->

<!--Corporate-->
<section class="bg-white key-areas-sec crm-title ptb-3">
    <h4>Corporate</h4>
</section>
<!--Corporate-->

<!--Corporate Clients-->
<section class="bg-grey client-crm-listing ptb-3">
    <div class="container">
    <ul class="gallery-slider" id="client-slider-wrapper">
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/Fujitsu-Logo.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/nihilent.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/atos.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/sciformix.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/nitor.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/tata.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/tata-steel.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/sears.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/resilinc.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/eteva.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/metro.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/hathway.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/wipro.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/principal.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/mahindra.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/sap.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/mochi.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/saama.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/infostretch.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/kirloskar.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/kc_og_general.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/ibm.png'); ?>" alt="">
        </li>
    </ul>
    </div>
</section>
<!--Corporate Clients-->

<!--Academic-->
<section class="bg-white key-areas-sec crm-title academic-title ptb-3">
    <h4>Academic</h4>
</section>
<!--Academic-->

<!--Academic Clients-->
<section class="bg-grey academic-crm-listing ptb-3">
    <div class="container">
    <ul class="gallery-slider" id="academic-slider-wrapper">
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/mit.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/flame.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/Vishwakarma.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/RIIM.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/aissms-coe.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/HNIMR.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/Suryadatta.png'); ?>" alt="">
        </li>
        <li>
            <img src="<?php echo $tag->getImageUri('assets/front/images/service/corporate-clients/logo-M.png'); ?>" alt="">
        </li>
    </ul>
    </div>
</section>
<!--Corporate Clients-->

<!--Upworking Workshops-->
<section class="bg-white workshops-title ptb-5">
    <h4>Upworking Workshops / Webinars</h4>
</section>
<!--Upworking Workshops-->